### ISSUE TITLE
Source maps are not allowed to be dynamically loaded in Safari

### ISSUE THREAD

**Issue by dhh** [guybedford/es-module-shims#228]
In Safari, and not Chrome or Firefox, source maps are not being loaded when going through the shim. Here are the errors:

<img width="927" alt="Screen Shot 2021-12-02 at 14 47 45" src="https://user-images.githubusercontent.com/2741/144434287-c8fcb834-c22b-430b-891b-705c70dd266e.png">

Here's the source map reference from one of the files:

<img width="502" alt="Screen Shot 2021-12-02 at 14 48 29" src="https://user-images.githubusercontent.com/2741/144434370-a8e55c0e-3b53-4b8b-8aea-9c93545403a0.png">

It loads correctly when you access it directly via https://peaceful-ravine-89231.herokuapp.com/assets/turbo.min.js-12ab1481b54e9f84d4561ac0e6e5328811dc5b233b7cba05444fcdee85912e46.map.

Tested on Safari 15.1 / M1.

**Comment by guybedford** [comment]
Good to know - I believe the issue here is the trailing `//!\n;` means the sourceMappingURL isn't picked up by the normalization step that is supposed to avoid this.

So if you try rewriting the original source to not include those lines it should work.

I could update the sourceMappingURL regex to support arbitrary trailing line comments or empty statements... let's just verify the fix works first?

**Comment by dhh** [comment]
Ah, lemme verify whether that's the issue!

**Comment by dhh** [comment]
Confirmed that this is the problem. When there's not extra stuff below the sourceMappingURL line, Safari is happy. Problem is that for a bunch of complicated reasons we need those extra lines in Rails 7.

**Comment by guybedford** [comment]
Fix released in 1.3.4 - let me know if there are any further issues.

**Comment by dhh** [comment]
Unfortunately that did not fix it. Still see the same issue with 1.3.4.

<img width="924" alt="Screen Shot 2021-12-03 at 09 58 29" src="https://user-images.githubusercontent.com/2741/144574609-ad65bbdc-d10a-47f3-aaa9-c4febd97b410.png">

**Comment by dhh** [comment]
Bingo. That solved it. Thanks a bunch! ✌️
